#! /usr/bin/env ruby

def shuffle_v2(array)

  array = array.map{|i| i.dup}
  
  probs = array.map{|arr| arr.length}

  total = 0
  
  probs.map!{|i| total += i}

  # at this point, probs is effectively a cumulative probability function for the bins.
  # I. E. the probability of bin i-or-less is (probs[i])/total
  
  randy = Array(1..total).shuffle

  out = []

  for rnum in randy

    ind = probs.index{|j| j >= rnum}
    out << array[ind].shift

  end

  return out
  
end


if __FILE__ == @PROGRAM_NAME

  array = ARGV.map do |path|

    Dir.glob(File.join(path,  "**/*")).select{|file| not File.directory?(file)}.sort

  end

  array << STDIN.readlines
  
  STDOUT.puts(shuffle_v2(array))

end
